---

-  {  include:  add.yml,                  tags:  add  }

# https://github.com/ansible/ansible/issues/18411
# include_role with with_items causes unexpected exception for role handlers
-  {  include:  name.yml,                 tags:  add, when: False  }
-  {  include:  name-without-handler.yml, tags:  add,        become: True  }

-  {  include:  partition.yml,            tags:  partition,  become: True  }
-  {  include:  crypt.yml,                tags:  crypt,      become: True  }
-  {  include:  mkfs.yml,                 tags:  mkfs,       become: True  }

# use rescan to force call to udevadm
