---

-  {  include:  add.yml,        tags:  add  }
-  {  include:  partition.yml,  tags:  partition,  become: True  }
-  {  include:  crypt.yml,      tags:  crypt,      become: True  }
-  {  include:  mkfs.yml,       tags:  mkfs,       become: True  }

# use rescan to force call to udevadm
