---

- name: Make filesystem

  filesystem:
    fstype: "{{ fstype }}"
    dev: &dev /dev/{{ vgname }}/{{ lvname }}
    opts: -m {{ reserved }}

- name: Mount filesystem

  mount:
    name: "{{ mountpoint }}"
    src: *dev
    fstype: "{{ fstype }}"
    opts: "{{ mountopts }}"
    state: mounted
